export type AdminEntityKind = "products" | "brands" | "promotions" | "posts";

export type AdminFieldOption = {
  label: string;
  value: string;
};

export type AdminField = {
  name: string;
  label: string;
  type:
    | "text"
    | "number"
    | "textarea"
    | "select"
    | "checkbox"
    | "date"
    | "url"
    | "file";
  placeholder?: string;
  help?: string;
  required?: boolean;
  options?: AdminFieldOption[];
  fullWidth?: boolean;
  min?: number;
  step?: string;
};

export type AdminItem = {
  id: string;
  title: string;
  subtitle: string;
  status: string;
  badge?: string;
  detail?: string;
  updatedAt: string;
  values: Record<string, string | boolean>;
};

export type AdminEntityConfig = {
  singular: string;
  plural: string;
  title: string;
  description: string;
  createLabel: string;
  searchPlaceholder: string;
  fields: AdminField[];
  items: AdminItem[];
  statusOptions: AdminFieldOption[];
};

export const entityConfigs: Record<AdminEntityKind, AdminEntityConfig> = {
  products: {
    singular: "produto",
    plural: "produtos",
    title: "Produtos",
    description:
      "Gerencie os itens que aparecem no catálogo e mantenha as informações comerciais em dia.",
    createLabel: "Novo produto",
    searchPlaceholder: "Buscar por nome, marca ou SKU",
    statusOptions: [
      { label: "Publicado", value: "published" },
      { label: "Rascunho", value: "draft" },
      { label: "Arquivado", value: "archived" },
    ],
    fields: [
      {
        name: "name",
        label: "Nome do produto",
        type: "text",
        placeholder: "Ex.: Coral Decora Seda 18 L",
        required: true,
        fullWidth: true,
      },
      {
        name: "slug",
        label: "Slug",
        type: "text",
        placeholder: "coral-decora-seda-18l",
        required: true,
        help: "Endereço amigável usado na página do produto.",
      },
      {
        name: "sku",
        label: "Código / SKU",
        type: "text",
        placeholder: "MM-CRL-001",
      },
      {
        name: "brandId",
        label: "Marca",
        type: "select",
        options: [
          { label: "Coral", value: "Coral" },
          { label: "Suvinil", value: "Suvinil" },
          { label: "Renner", value: "Renner" },
          { label: "Tigre", value: "Tigre" },
          { label: "Atlas", value: "Atlas" },
        ],
      },
      {
        name: "categoryId",
        label: "Categoria principal",
        type: "select",
        options: [
          { label: "Tintas", value: "Tintas" },
          { label: "Acessórios", value: "Acessórios" },
          { label: "Ferramentas", value: "Ferramentas" },
          { label: "Complementos", value: "Complementos" },
        ],
      },
      {
        name: "application",
        label: "Aplicação",
        type: "select",
        options: [
          { label: "Interior", value: "Interior" },
          { label: "Exterior", value: "Exterior" },
          { label: "Interior e exterior", value: "Interior e exterior" },
          { label: "Madeira e metal", value: "Madeira e metal" },
        ],
      },
      {
        name: "finish",
        label: "Acabamento",
        type: "text",
        placeholder: "Fosco, acetinado, semibrilho…",
      },
      {
        name: "color",
        label: "Cor / base",
        type: "text",
        placeholder: "Branco, base A, incolor…",
      },
      {
        name: "packageSize",
        label: "Embalagem",
        type: "text",
        placeholder: "18 L",
      },
      {
        name: "unit",
        label: "Unidade",
        type: "text",
        placeholder: "unidade",
      },
      {
        name: "price",
        label: "Preço de referência",
        type: "number",
        placeholder: "0,00",
        min: 0,
        step: "0.01",
      },
      {
        name: "compareAtPrice",
        label: "Preço anterior",
        type: "number",
        placeholder: "0,00",
        min: 0,
        step: "0.01",
      },
      {
        name: "costPrice",
        label: "Custo interno",
        type: "number",
        placeholder: "0,00",
        min: 0,
        step: "0.01",
        help: "Informação administrativa; não é exibida no site.",
      },
      {
        name: "stockQuantity",
        label: "Estoque",
        type: "number",
        placeholder: "0",
        min: 0,
      },
      {
        name: "status",
        label: "Status",
        type: "select",
        required: true,
        options: [
          { label: "Publicado", value: "published" },
          { label: "Rascunho", value: "draft" },
          { label: "Arquivado", value: "archived" },
        ],
      },
      {
        name: "shortDescription",
        label: "Descrição curta",
        type: "textarea",
        placeholder: "Resumo que será exibido nos cards e resultados de busca.",
        fullWidth: true,
      },
      {
        name: "description",
        label: "Descrição completa",
        type: "textarea",
        placeholder: "Detalhes, benefícios, rendimento e recomendações.",
        fullWidth: true,
      },
      {
        name: "publishedAt",
        label: "Data de publicação",
        type: "date",
      },
      {
        name: "seoTitle",
        label: "Título para SEO",
        type: "text",
        placeholder: "Até 70 caracteres",
      },
      {
        name: "seoDescription",
        label: "Descrição para SEO",
        type: "textarea",
        placeholder: "Descrição que pode aparecer nos resultados de busca.",
        fullWidth: true,
      },
      {
        name: "image",
        label: "Imagem principal",
        type: "file",
        help: "PNG, JPG, WebP ou AVIF, com até 10 MB.",
        fullWidth: true,
      },
      {
        name: "isFeatured",
        label: "Destacar este produto na página inicial",
        type: "checkbox",
        fullWidth: true,
      },
    ],
    items: [
      {
        id: "demo-product-1",
        title: "Coral Decora Seda 18 L",
        subtitle: "Coral • Tinta acrílica premium",
        status: "published",
        badge: "Destaque",
        detail: "R$ 489,90",
        updatedAt: "Hoje, 09:42",
        values: {
          name: "Coral Decora Seda 18 L",
          slug: "coral-decora-seda-18l",
          sku: "MM-CRL-001",
          brandId: "Coral",
          categoryId: "Tintas",
          application: "Interior",
          finish: "Acetinado",
          color: "Branco",
          packageSize: "18 L",
          unit: "lata",
          price: "489.90",
          compareAtPrice: "",
          costPrice: "",
          stockQuantity: "18",
          status: "published",
          shortDescription:
            "Tinta acrílica premium de alta cobertura e acabamento acetinado.",
          description: "",
          publishedAt: "2026-07-20",
          seoTitle: "",
          seoDescription: "",
          isFeatured: true,
        },
      },
      {
        id: "demo-product-2",
        title: "Suvinil Fosco Completo 18 L",
        subtitle: "Suvinil • Tinta acrílica",
        status: "published",
        detail: "R$ 379,90",
        updatedAt: "Ontem, 16:18",
        values: {
          name: "Suvinil Fosco Completo 18 L",
          slug: "suvinil-fosco-completo-18l",
          sku: "MM-SUV-014",
          brandId: "Suvinil",
          categoryId: "Tintas",
          application: "Interior e exterior",
          finish: "Fosco",
          color: "Branco",
          packageSize: "18 L",
          unit: "lata",
          price: "379.90",
          compareAtPrice: "",
          costPrice: "",
          stockQuantity: "24",
          status: "published",
          shortDescription: "Excelente cobertura para ambientes internos e externos.",
          description: "",
          publishedAt: "2026-07-18",
          seoTitle: "",
          seoDescription: "",
          isFeatured: false,
        },
      },
      {
        id: "demo-product-3",
        title: "Renner Rekolor Pró 3,6 L",
        subtitle: "Renner • Tinta acrílica",
        status: "draft",
        detail: "R$ 129,90",
        updatedAt: "24 jul., 11:05",
        values: {
          name: "Renner Rekolor Pró 3,6 L",
          slug: "renner-rekolor-pro-36l",
          sku: "MM-RNR-008",
          brandId: "Renner",
          categoryId: "Tintas",
          application: "Interior",
          finish: "Fosco",
          color: "Branco",
          packageSize: "3,6 L",
          unit: "galão",
          price: "129.90",
          compareAtPrice: "",
          costPrice: "",
          stockQuantity: "8",
          status: "draft",
          shortDescription: "Praticidade e ótimo rendimento para sua reforma.",
          description: "",
          publishedAt: "",
          seoTitle: "",
          seoDescription: "",
          isFeatured: false,
        },
      },
      {
        id: "demo-product-4",
        title: "Rolo Atlas Antirrespingo 23 cm",
        subtitle: "Atlas • Acessório para pintura",
        status: "published",
        detail: "R$ 32,90",
        updatedAt: "22 jul., 14:30",
        values: {
          name: "Rolo Atlas Antirrespingo 23 cm",
          slug: "rolo-atlas-antirrespingo-23cm",
          sku: "MM-ATL-027",
          brandId: "Atlas",
          categoryId: "Acessórios",
          application: "Interior e exterior",
          finish: "",
          color: "",
          packageSize: "Unidade",
          unit: "unidade",
          price: "32.90",
          compareAtPrice: "",
          costPrice: "",
          stockQuantity: "42",
          status: "published",
          shortDescription: "Rolo de lã sintética para acabamento uniforme.",
          description: "",
          publishedAt: "2026-07-10",
          seoTitle: "",
          seoDescription: "",
          isFeatured: true,
        },
      },
    ],
  },
  brands: {
    singular: "marca",
    plural: "marcas",
    title: "Marcas",
    description:
      "Organize os fabricantes disponíveis na loja e escolha quais terão destaque no site.",
    createLabel: "Nova marca",
    searchPlaceholder: "Buscar uma marca",
    statusOptions: [
      { label: "Ativa", value: "active" },
      { label: "Inativa", value: "inactive" },
    ],
    fields: [
      {
        name: "name",
        label: "Nome da marca",
        type: "text",
        placeholder: "Ex.: Suvinil",
        required: true,
      },
      {
        name: "slug",
        label: "Slug",
        type: "text",
        placeholder: "suvinil",
        required: true,
      },
      {
        name: "website",
        label: "Site oficial",
        type: "url",
        placeholder: "https://...",
      },
      {
        name: "displayOrder",
        label: "Ordem de exibição",
        type: "number",
        placeholder: "0",
        min: 0,
      },
      {
        name: "description",
        label: "Descrição",
        type: "textarea",
        placeholder: "Breve apresentação da marca.",
        fullWidth: true,
      },
      {
        name: "seoTitle",
        label: "Título para SEO",
        type: "text",
        placeholder: "Até 70 caracteres",
      },
      {
        name: "seoDescription",
        label: "Descrição para SEO",
        type: "textarea",
        placeholder: "Breve descrição para mecanismos de busca.",
        fullWidth: true,
      },
      {
        name: "logo",
        label: "Logotipo",
        type: "file",
        help: "Prefira PNG ou WebP com fundo transparente.",
        fullWidth: true,
      },
      {
        name: "isActive",
        label: "Marca ativa no catálogo",
        type: "checkbox",
        fullWidth: true,
      },
      {
        name: "isFeatured",
        label: "Exibir entre as marcas em destaque",
        type: "checkbox",
        fullWidth: true,
      },
    ],
    items: [
      {
        id: "demo-brand-1",
        title: "Coral",
        subtitle: "42 produtos associados",
        status: "active",
        badge: "Destaque",
        detail: "Ordem 1",
        updatedAt: "Hoje, 08:15",
        values: {
          name: "Coral",
          slug: "coral",
          website: "https://www.coral.com.br",
          displayOrder: "1",
          description: "Tintas e soluções para transformar ambientes.",
          seoTitle: "",
          seoDescription: "",
          isActive: true,
          isFeatured: true,
        },
      },
      {
        id: "demo-brand-2",
        title: "Suvinil",
        subtitle: "38 produtos associados",
        status: "active",
        badge: "Destaque",
        detail: "Ordem 2",
        updatedAt: "25 jul., 10:40",
        values: {
          name: "Suvinil",
          slug: "suvinil",
          website: "https://www.suvinil.com.br",
          displayOrder: "2",
          description: "Cores, inovação e proteção para todos os projetos.",
          seoTitle: "",
          seoDescription: "",
          isActive: true,
          isFeatured: true,
        },
      },
      {
        id: "demo-brand-3",
        title: "Renner",
        subtitle: "27 produtos associados",
        status: "active",
        detail: "Ordem 3",
        updatedAt: "23 jul., 14:20",
        values: {
          name: "Renner",
          slug: "renner",
          website: "",
          displayOrder: "3",
          description: "Linha completa de tintas imobiliárias.",
          seoTitle: "",
          seoDescription: "",
          isActive: true,
          isFeatured: false,
        },
      },
      {
        id: "demo-brand-4",
        title: "Atlas",
        subtitle: "31 produtos associados",
        status: "inactive",
        detail: "Ordem 5",
        updatedAt: "18 jul., 09:10",
        values: {
          name: "Atlas",
          slug: "atlas",
          website: "",
          displayOrder: "5",
          description: "Ferramentas e acessórios para pintura.",
          seoTitle: "",
          seoDescription: "",
          isActive: false,
          isFeatured: false,
        },
      },
    ],
  },
  promotions: {
    singular: "promoção",
    plural: "promoções",
    title: "Promoções",
    description:
      "Planeje campanhas, defina períodos de exibição e destaque as melhores ofertas.",
    createLabel: "Nova promoção",
    searchPlaceholder: "Buscar uma campanha",
    statusOptions: [
      { label: "Publicada", value: "published" },
      { label: "Rascunho", value: "draft" },
      { label: "Arquivada", value: "archived" },
    ],
    fields: [
      {
        name: "name",
        label: "Nome da campanha",
        type: "text",
        placeholder: "Ex.: Semana da Pintura",
        required: true,
        fullWidth: true,
      },
      {
        name: "slug",
        label: "Slug",
        type: "text",
        placeholder: "semana-da-pintura",
        required: true,
      },
      {
        name: "badge",
        label: "Selo",
        type: "text",
        placeholder: "Oferta especial",
      },
      {
        name: "discountType",
        label: "Tipo de desconto",
        type: "select",
        required: true,
        options: [
          { label: "Percentual", value: "percentage" },
          { label: "Valor fixo", value: "fixed_amount" },
        ],
      },
      {
        name: "discountValue",
        label: "Desconto",
        type: "number",
        placeholder: "10",
        min: 0,
        step: "0.01",
      },
      {
        name: "startsAt",
        label: "Início",
        type: "date",
        required: true,
      },
      {
        name: "endsAt",
        label: "Término",
        type: "date",
        required: true,
      },
      {
        name: "status",
        label: "Status",
        type: "select",
        required: true,
        options: [
          { label: "Publicada", value: "published" },
          { label: "Rascunho", value: "draft" },
          { label: "Arquivada", value: "archived" },
        ],
      },
      {
        name: "productId",
        label: "Produto participante",
        type: "select",
        help: "Associe ao menos o principal produto da campanha.",
        options: [
          {
            label: "Coral Decora Seda 18 L",
            value: "Coral Decora Seda 18 L",
          },
          {
            label: "Suvinil Fosco Completo 18 L",
            value: "Suvinil Fosco Completo 18 L",
          },
          {
            label: "Renner Rekolor Pró 3,6 L",
            value: "Renner Rekolor Pró 3,6 L",
          },
        ],
      },
      {
        name: "promotionalPrice",
        label: "Preço promocional",
        type: "number",
        placeholder: "0,00",
        min: 0,
        step: "0.01",
      },
      {
        name: "description",
        label: "Descrição da campanha",
        type: "textarea",
        placeholder: "Explique a oferta em poucas palavras.",
        fullWidth: true,
      },
      {
        name: "terms",
        label: "Termos e condições",
        type: "textarea",
        placeholder: "Regras, limites e condições aplicáveis.",
        fullWidth: true,
      },
      {
        name: "banner",
        label: "Banner",
        type: "file",
        help: "Imagem horizontal em JPG, PNG, WebP ou AVIF.",
        fullWidth: true,
      },
      {
        name: "isActive",
        label: "Ativar campanha no período definido",
        type: "checkbox",
        fullWidth: true,
      },
    ],
    items: [
      {
        id: "demo-promotion-1",
        title: "Semana da Pintura",
        subtitle: "10% em tintas selecionadas",
        status: "published",
        badge: "Ativa",
        detail: "Até 03 ago.",
        updatedAt: "Hoje, 10:05",
        values: {
          name: "Semana da Pintura",
          slug: "semana-da-pintura",
          badge: "Oferta especial",
          discountType: "percentage",
          discountValue: "10",
          startsAt: "2026-07-27",
          endsAt: "2026-08-03",
          status: "published",
          productId: "Coral Decora Seda 18 L",
          promotionalPrice: "439.90",
          description: "Condições especiais em tintas selecionadas.",
          terms: "Válido enquanto durarem os estoques.",
          isActive: true,
        },
      },
      {
        id: "demo-promotion-2",
        title: "Festival de Cores",
        subtitle: "15% em produtos Coral",
        status: "published",
        badge: "Ativa",
        detail: "Até 10 ago.",
        updatedAt: "Ontem, 13:50",
        values: {
          name: "Festival de Cores",
          slug: "festival-de-cores",
          badge: "Festival",
          discountType: "percentage",
          discountValue: "15",
          startsAt: "2026-08-01",
          endsAt: "2026-08-10",
          status: "published",
          productId: "Suvinil Fosco Completo 18 L",
          promotionalPrice: "322.90",
          description: "Uma seleção de cores Coral com preços especiais.",
          terms: "Não cumulativo com outras ofertas.",
          isActive: true,
        },
      },
      {
        id: "demo-promotion-3",
        title: "Oferta para Pintores",
        subtitle: "Condição especial para profissionais",
        status: "draft",
        detail: "Sem data",
        updatedAt: "21 jul., 15:42",
        values: {
          name: "Oferta para Pintores",
          slug: "oferta-para-pintores",
          badge: "Profissional",
          discountType: "fixed_amount",
          discountValue: "50",
          startsAt: "2026-08-15",
          endsAt: "2026-08-22",
          status: "draft",
          productId: "",
          promotionalPrice: "",
          description: "Benefícios para pintores parceiros da MM Tintas.",
          terms: "",
          isActive: false,
        },
      },
    ],
  },
  posts: {
    singular: "artigo",
    plural: "artigos",
    title: "Blog",
    description:
      "Crie conteúdos úteis para seus clientes e fortaleça a presença da MM Tintas nas buscas.",
    createLabel: "Novo artigo",
    searchPlaceholder: "Buscar por título ou assunto",
    statusOptions: [
      { label: "Publicado", value: "published" },
      { label: "Rascunho", value: "draft" },
      { label: "Arquivado", value: "archived" },
    ],
    fields: [
      {
        name: "title",
        label: "Título",
        type: "text",
        placeholder: "Um título claro e interessante",
        required: true,
        fullWidth: true,
      },
      {
        name: "slug",
        label: "Slug",
        type: "text",
        placeholder: "titulo-do-artigo",
        required: true,
      },
      {
        name: "categoryId",
        label: "Categoria",
        type: "select",
        options: [
          { label: "Dicas de pintura", value: "Dicas de pintura" },
          { label: "Cores e tendências", value: "Cores e tendências" },
          { label: "Preparação", value: "Preparação" },
          { label: "Produtos", value: "Produtos" },
        ],
      },
      {
        name: "status",
        label: "Status",
        type: "select",
        required: true,
        options: [
          { label: "Publicado", value: "published" },
          { label: "Rascunho", value: "draft" },
          { label: "Arquivado", value: "archived" },
        ],
      },
      {
        name: "publishedAt",
        label: "Data de publicação",
        type: "date",
      },
      {
        name: "excerpt",
        label: "Resumo",
        type: "textarea",
        placeholder: "Uma introdução curta para o card do artigo.",
        fullWidth: true,
      },
      {
        name: "content",
        label: "Conteúdo",
        type: "textarea",
        placeholder: "Escreva o conteúdo do artigo…",
        required: true,
        fullWidth: true,
      },
      {
        name: "coverImage",
        label: "Imagem de capa",
        type: "file",
        help: "Recomendado: proporção 16:9 e pelo menos 1200 px de largura.",
        fullWidth: true,
      },
      {
        name: "seoTitle",
        label: "Título para SEO",
        type: "text",
        placeholder: "Até 60 caracteres",
        fullWidth: true,
      },
      {
        name: "seoDescription",
        label: "Descrição para SEO",
        type: "textarea",
        placeholder: "Até 160 caracteres",
        fullWidth: true,
      },
    ],
    items: [
      {
        id: "demo-post-1",
        title: "Como escolher a tinta ideal para cada ambiente",
        subtitle: "Dicas de pintura • 6 min de leitura",
        status: "published",
        badge: "Destaque",
        detail: "28 jul. 2026",
        updatedAt: "Hoje, 08:35",
        values: {
          title: "Como escolher a tinta ideal para cada ambiente",
          slug: "como-escolher-tinta-ideal-cada-ambiente",
          categoryId: "Dicas de pintura",
          status: "published",
          publishedAt: "2026-07-28",
          excerpt:
            "Entenda os acabamentos e encontre a solução certa para cada espaço.",
          content:
            "Escolher a tinta certa começa entendendo o uso do ambiente, a iluminação e o acabamento desejado.",
          seoTitle: "Como escolher a tinta ideal | MM Tintas",
          seoDescription:
            "Guia prático para escolher tintas para ambientes internos e externos.",
        },
      },
      {
        id: "demo-post-2",
        title: "5 passos para preparar a parede antes de pintar",
        subtitle: "Preparação • 4 min de leitura",
        status: "published",
        detail: "24 jul. 2026",
        updatedAt: "24 jul., 10:10",
        values: {
          title: "5 passos para preparar a parede antes de pintar",
          slug: "preparar-parede-antes-de-pintar",
          categoryId: "Preparação",
          status: "published",
          publishedAt: "2026-07-24",
          excerpt: "Um bom resultado depende de uma preparação bem-feita.",
          content:
            "Limpeza, correção de imperfeições e selagem são etapas essenciais antes da pintura.",
          seoTitle: "Como preparar a parede antes de pintar",
          seoDescription:
            "Veja cinco passos essenciais para preparar paredes antes da pintura.",
        },
      },
      {
        id: "demo-post-3",
        title: "Tendências de cores para renovar a casa",
        subtitle: "Cores e tendências • 5 min de leitura",
        status: "draft",
        detail: "Não publicado",
        updatedAt: "22 jul., 17:05",
        values: {
          title: "Tendências de cores para renovar a casa",
          slug: "tendencias-de-cores-para-renovar-a-casa",
          categoryId: "Cores e tendências",
          status: "draft",
          publishedAt: "",
          excerpt: "Inspire-se em combinações que trazem conforto e personalidade.",
          content:
            "Tons naturais, verdes acolhedores e azuis profundos seguem em destaque.",
          seoTitle: "",
          seoDescription: "",
        },
      },
    ],
  },
};
